/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#F7931E",
        "primary-hover": "#E08010",
        "primary-dark": "#D6780E",
        "primary-game": "#F59E0B",
        "primary-tv": "#FB923C",
        secondary: "#10B981",
        "secondary-tv": "#FCD34D",
        "background-light": "#FFFDF5",
        "background-light-tv": "#FFFBF5",
        "background-dark": "#121212",
        "background-dark-game": "#0F172A",
        "background-dark-tv": "#1F1D2B",
        "surface-dark-tv": "#2D2B3B",
        "surface-light": "#FFFFFF",
        "surface-dark": "#1E1E1E",
        "surface-dark-lighter": "#334155",
        "text-main": "#2D2D2D",
        "text-sub": "#666666",
        "text-dark-main": "#EAEAEA",
        "text-dark-sub": "#A0A0A0",
        "pastel-yellow": "#FFF8E1",
        "pastel-green": "#E8F5E9",
        "pastel-blue": "#E3F2FD",
        "pastel-purple": "#F3E5F5",
        "pastel-red": "#FFEBEE",
        "pastel-orange": "#FFF3E0",
        "primary-settings": "#F97316",
        "soft-orange": "#FFF7ED",
        "soft-green": "#F0FDF4",
        "soft-purple": "#FAF5FF",
        "accent-toggle": "#10B981",
      },
      fontFamily: {
        display: ["Nunito", "Lexend", "sans-serif"],
        "display-tv": ["Quicksand", "sans-serif"],
        body: ["Inter", "sans-serif"],
        rounded: ["Quicksand", "sans-serif"],
      },
      borderRadius: {
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        '4xl': '2.5rem',
      },
      boxShadow: {
        'soft': '0 10px 40px -10px rgba(0,0,0,0.05)',
        'card': '0 4px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px -1px rgba(0, 0, 0, 0.02)',
        'button': '0 4px 14px 0 rgba(247, 147, 30, 0.39)',
        'inner-light': 'inset 0 2px 4px 0 rgba(255, 255, 255, 0.3)',
        'glow': '0 0 20px rgba(245, 158, 11, 0.4)',
        'inner-soft': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        '3d': '0 4px 0px 0px rgba(0,0,0,0.1)',
        '3d-hover': '0 2px 0px 0px rgba(0,0,0,0.1)',
      }
    },
  },
  plugins: [],
}

